[tool.pylint.messages_control]

disable = [
    "consider-using-f-string",
    "invalid-name",
    "unidiomatic-typecheck",
    "redefined-builtin",
    "unused-variable",
    "ungrouped-imports",
    "unused-import",
    "cell-var-from-loop",
    "bare-except",
    "line-too-long",
    "redefined-outer-name",
    "too-many-locals",
    "inconsistent-return-statements",
    "too-many-arguments",
    "no-else-return",
    "duplicate-code"
    ]

[tool.black]
line-length = 80
target-version = ['py39']
skip-string-normalization = true

[tool.isort]
length_sort = true